// Copyright 2026 Antmicro <antmicro.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#include "GlobalOpts.h"

#include "FaultStrategyFactory.h"

#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
#include <nlohmann/json.hpp>

#include <fstream>
#include <iostream>

ABSL_FLAG(std::string, sig_path_prefix, "", "Prefix for signal paths, i.e. `top`.");
ABSL_FLAG(std::string, top_module, "", "Name of the top module.");
ABSL_FLAG(std::string, top_instance, "", "Name of the top module instance.");
ABSL_FLAG(std::string, netlist_path, "", "Path to the netlist generated by Yosys.");
ABSL_FLAG(std::optional<std::uint64_t>,
          simulation_time,
          std::nullopt,
          "Total duration of the simulation.");
const std::uint64_t simulation_time_default = 1000;
ABSL_FLAG(std::optional<std::uint64_t>,
          num_of_events,
          std::nullopt,
          "Number of generated single-event effects.");
const std::uint64_t num_of_events_default = 10;
ABSL_FLAG(std::optional<std::uint32_t>, seed, std::nullopt, "Random seed.");
const std::uint64_t seed_default = 42;
ABSL_FLAG(std::optional<std::string>,
          fault_campaign_out,
          std::nullopt,
          "Path for generated fault campaign file.");
ABSL_FLAG(std::string,
          config_file,
          "",
          "Path to configuration file. If this flag is present, all others are ignored.");
ABSL_FLAG(std::uint64_t,
          campaign_number,
          1,
          "Number of campaigns to generate. If number is greater than 1, `--fault_campaign_out` is "
          "treated as a directory");
ABSL_FLAG(std::optional<std::uint32_t>, thread_number, std::nullopt, "Number of threads to use.");
const std::uint32_t thread_number_default = 1;
const char* fault_campaign_out_file_defualt = "fault_campaign_out.csv";
const char* fault_campaign_out_directory_defualt = "fault_campaign_out";
ABSL_FLAG(std::vector<std::string>,
          liberty_paths,
          {},
          "List of comma separated paths to liberty files.");

void from_json(const nlohmann::json& json, FaultStrategy::Config& config) {
    if (absl::GetFlag(FLAGS_num_of_events)) {
        config.num_of_events = absl::GetFlag(FLAGS_num_of_events).value();
    } else {
        config.num_of_events = json.value("num_of_events", num_of_events_default);
    }

    if (absl::GetFlag(FLAGS_seed)) {
        config.seed = absl::GetFlag(FLAGS_seed).value();
    } else {
        config.seed = json.value("seed", seed_default);
    }

    if (absl::GetFlag(FLAGS_simulation_time)) {
        config.simulation_time = absl::GetFlag(FLAGS_simulation_time).value();
    } else {
        config.simulation_time = json.value("simulation_time", simulation_time_default);
    }
}

void from_json(const nlohmann::json& json, GlobalOpts& opts) {
    const auto& model = json.at("model");
    const auto& params = json["params"];

    FaultStrategy::Config config = params.get<FaultStrategy::Config>();
    opts.strategy = FaultStrategyFactory::buildFromJson(config, model);

#define GET_OR_DEFAULT(name) \
    opts.name = params.value(#name, absl::GetFlagReflectionHandle(FLAGS_##name).DefaultValue())
    GET_OR_DEFAULT(sig_path_prefix);
    GET_OR_DEFAULT(top_module);
    GET_OR_DEFAULT(top_instance);
    GET_OR_DEFAULT(netlist_path);
#undef GET_OR_DEFAULT
    opts.campaign_number = params.value(
        "campaign_number",
        std::stoi(absl::GetFlagReflectionHandle(FLAGS_campaign_number).DefaultValue()));
    if (absl::GetFlag(FLAGS_thread_number)) {
        opts.thread_number = absl::GetFlag(FLAGS_thread_number).value();
    } else {
        opts.thread_number = params.value("thread_number", thread_number_default);
    }
    opts.liberty_paths = params.value<std::vector<std::string>>("liberty_paths", {});

    if (absl::GetFlag(FLAGS_fault_campaign_out)) {
        opts.fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
    } else if (params.contains("fault_campaign_out")) {
        opts.fault_campaign_out = params["fault_campaign_out"].get<std::string>();
    } else {
        if (opts.campaign_number == 1) {
            opts.fault_campaign_out = fault_campaign_out_file_defualt;
        } else {
            opts.fault_campaign_out = fault_campaign_out_directory_defualt;
        }
    }
    opts.strategy = FaultStrategyFactory::buildFromJson(config, model);
}

GlobalOpts GlobalOpts::parse_cmd_args(int argc, char** argv) {
    absl::ParseCommandLine(argc, argv);

    std::string config_filepath = absl::GetFlag(FLAGS_config_file);
    if (config_filepath.empty()) {
        FaultStrategy::Config config = {
            absl::GetFlag(FLAGS_num_of_events).value_or(num_of_events_default),
            absl::GetFlag(FLAGS_seed).value_or(seed_default),
            absl::GetFlag(FLAGS_simulation_time).value_or(simulation_time_default)};

        std::uint64_t campaign_number = absl::GetFlag(FLAGS_campaign_number);
        std::string fault_campaign_out;
        if (absl::GetFlag(FLAGS_fault_campaign_out)) {
            fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out).value();
        } else {
            if (campaign_number == 1) {
                fault_campaign_out = fault_campaign_out_file_defualt;
            } else {
                fault_campaign_out = fault_campaign_out_directory_defualt;
            }
        }

        // TODO Check that all required flags were passed
        return {
            .sig_path_prefix = absl::GetFlag(FLAGS_sig_path_prefix),
            .top_module = absl::GetFlag(FLAGS_top_module),
            .top_instance = absl::GetFlag(FLAGS_top_instance),
            .netlist_path = absl::GetFlag(FLAGS_netlist_path),
            .fault_campaign_out = fault_campaign_out,
            .campaign_number = campaign_number,
            .thread_number = absl::GetFlag(FLAGS_thread_number).value_or(thread_number_default),
            .strategy = FaultStrategyFactory::defaultStrategy(config),
            .liberty_paths = absl::GetFlag(FLAGS_liberty_paths),
        };
    } else {
        try {
            std::ifstream config_file{config_filepath};
            if (!config_file) {
                std::error_code ec(errno, std::generic_category());
                std::cerr << "%%Error: Failed to open '" << config_filepath << "': " << ec.message()
                          << "\n";
                std::exit(1);
            }
            const auto config_json = nlohmann::json::parse(config_file);

            return config_json.get<GlobalOpts>();
        } catch (std::exception& error) {
            std::cerr << "%%Error: Ill formed config file [" << config_filepath << "]\n";
            std::cerr << error.what() << "\n";
            std::exit(1);
        }
    }
}
