// Copyright 2026 Antmicro <antmicro.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#include "GlobalOpts.h"

#include "FaultStrategyFactory.h"

#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
#include <nlohmann/json.hpp>

#include <fstream>
#include <iostream>

ABSL_FLAG(std::string, sig_path_prefix, "", "Prefix for signal paths, i.e. `top`.");
ABSL_FLAG(std::string, top_module, "", "Name of the top module.");
ABSL_FLAG(std::string, top_instance, "", "Name of the top module instance.");
ABSL_FLAG(std::string, netlist_path, "", "Path to the netlist generated by Yosys.");
ABSL_FLAG(std::uint64_t, simulation_time, 1000, "Total duration of the simulation.");
ABSL_FLAG(std::uint64_t, num_of_events, 10, "Number of generated single-event effects.");
ABSL_FLAG(std::uint32_t, seed, 42, "Random seed.");
ABSL_FLAG(std::string,
          fault_campaign_out,
          "fault_campaign_out.csv",
          "Path for generated fault campaign file.");
ABSL_FLAG(std::string,
          config_file,
          "",
          "Path to configuration file. If this flag is present, all others are ignored.");
ABSL_FLAG(std::vector<std::string>,
          liberty_paths,
          {},
          "List of comma separated paths to liberty files.");

#define GET_OR_DEFAULT(name) \
    json.value(#name, std::stoi(absl::GetFlagReflectionHandle(FLAGS_##name).DefaultValue()))

void from_json(const nlohmann::json& json, FaultStrategy::Config& config) {
    config.num_of_events = GET_OR_DEFAULT(num_of_events);
    config.seed = GET_OR_DEFAULT(seed);
    config.simulation_time = GET_OR_DEFAULT(simulation_time);
}
#undef GET_OR_DEFAULT

void from_json(const nlohmann::json& json, GlobalOpts& opts) {
    const auto& model = json.at("model");
    const auto& params = json["params"];

    FaultStrategy::Config config = params.get<FaultStrategy::Config>();
#define GET_OR_DEFAULT(name) \
    opts.name = params.value(#name, absl::GetFlagReflectionHandle(FLAGS_##name).DefaultValue())
    GET_OR_DEFAULT(sig_path_prefix);
    GET_OR_DEFAULT(top_module);
    GET_OR_DEFAULT(top_instance);
    GET_OR_DEFAULT(netlist_path);
    // Below line is forced by setting being called netlist when it's commandline argument and
    // netlist_path when it is in json config
    GET_OR_DEFAULT(fault_campaign_out);
    opts.liberty_paths = params.value<std::vector<std::string>>("liberty_paths", {});
#undef GET_OR_DEFAULT

    opts.strategy = FaultStrategyFactory::build_from_json(config, model);
}

GlobalOpts GlobalOpts::parse_cmd_args(int argc, char** argv) {
    absl::ParseCommandLine(argc, argv);

    std::string config_filepath = absl::GetFlag(FLAGS_config_file);
    if (config_filepath.empty()) {
        FaultStrategy::Config config = {absl::GetFlag(FLAGS_num_of_events),
                                        absl::GetFlag(FLAGS_seed),
                                        absl::GetFlag(FLAGS_simulation_time)};
        // TODO Check that all required flags were passed
        return {
            .sig_path_prefix = absl::GetFlag(FLAGS_sig_path_prefix),
            .top_module = absl::GetFlag(FLAGS_top_module),
            .top_instance = absl::GetFlag(FLAGS_top_instance),
            .netlist_path = absl::GetFlag(FLAGS_netlist_path),
            .fault_campaign_out = absl::GetFlag(FLAGS_fault_campaign_out),
            .strategy = FaultStrategyFactory::default_strategy(config),
            .liberty_paths = absl::GetFlag(FLAGS_liberty_paths),
        };
    } else {
        try {
            std::ifstream config_file{config_filepath};
            if (!config_file) {
                std::error_code ec(errno, std::generic_category());
                std::cerr << "Failed to open '" << config_filepath << "': " << ec.message() << "\n";
                std::exit(1);
            }
            const auto config_json = nlohmann::json::parse(config_file);

            return config_json.get<GlobalOpts>();
        } catch (std::exception& error) {
            std::cerr << "Ill formed config file [" << config_filepath << "]\n";
            std::cerr << error.what() << "\n";
            std::exit(1);
        }
    }
}
